version: "3"
tasks:
  lint:
    aliases:
      - lint
    desc: "Generate code from proto files"
    vars:
      PROTO_PATH: user post stream
    cmd: docker run -t --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.55.2 golangci-lint run -v
